config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/auths' => 'auths#index'
  # get '/profile' => 'auths#show'
  get '/profile' => 'auths#profile'
  get '/home' => 'home#index'
  resources :home
  resources :auths
  resources :skills
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks:  "users/omniauth_callbacks" 
  }

  # devise_scope :user do
  #   delete "/sign_out", :to => 'sessions#destroy'
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="content">
</div>
<footer id="myFooter">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <h2 class="logo"><a href="#"> LOGO </a></h2>
      </div>
      <div class="col-sm-2">
        <h5>Get started</h5>
        <ul>
          <li><a href="home">Home</a></li>
          <!-- <li><a href="auths">Sign In</a></li> -->
          <!-- <li><a href="#">Downloads</a></li> -->
        </ul>
      </div>
      <div class="col-sm-2">
        <h5>About us</h5>
        <ul>
          <li><a href="#">Company Information</a></li>
          <li><a href="#">Contact us</a></li>
          <li><a href="#">Reviews</a></li>
        </ul>
      </div>
      <div class="col-sm-2">
        <h5>Support</h5>
        <ul>
          <li><a href="#">FAQ</a></li>
          <li><a href="#">Help desk</a></li>
          <li><a href="#">Forums</a></li>
        </ul>
      </div>
      <div class="col-sm-3">
        <div class="social-networks">
          <a href="users/auth/linkedin" class="twitter"><i class="fa fa-linkedin"></i></a>
          <a href="users/auth/facebook" class="facebook"><i class="fa fa-facebook"></i></a>
          <a href="users/auth/google_oauth2" class="google"><i class="fa fa-google-plus"></i></a>
        </div>
        <button type="button" class="btn btn-default">Contact us</button>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <p>© 2016 Copyright Text </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div style="background-color: #3c3d41">
	<nav class="navbar navbar-expand-lg navbar-light bg-faded">
		<%= link_to 'WeekendPros', home_path,class:"navbar-brand", id:"navbar_color" %>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div id="navbarNavDropdown" class="navbar-collapse collapse  justify-content-end" style="margin-right: 5%">
			<ul class="navbar-nav">
				<li class="nav-item">
					<%= link_to 'Home', home_path,class:"nav-link", id:"navbar_color" %>
				</li>
				<li class="nav-item">
					<a class="nav-link" id="navbar_color" >About</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" id="navbar_color">Content us</a>
				</li>
				<li class="nav-item">
					<% if user_signed_in? %> 
					<div class="dropdown">
						<a data-toggle="dropdown">
							<%= image_tag current_user.image, class:"nav-link rounded-circle"%>
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>   
						</ul>
					</div>
					<%else%>
					<%= link_to('Sing in', auths_path, class:"nav-link", id:"navbar_color") %>
					<% end %>
				</li>
			</ul>
		</div>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeekendPros</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application'%>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <div class="top">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/weekendpro.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeekendPros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'weekendpro/application' %>
    <%= javascript_include_tag 'weekendpro/application' %>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'layouts/header'%>
      <div class="top">
        <%= yield %>
      </div>
    <%= render 'layouts/footer'%>
  </body>
</html>